# Config for RP_Sign
# Language: ru or en
lang: en

# Message Settings
# Use HEX colors in the format <#RRGGBB>
messages:
  prefix: "<#00BFFF>[RP_Sign] <#FFFFFF>"
  success-color: "<#32CD32>"
  error-color: "<#FF4500>"
  info-color: "<#1E90FF>"
  warning-color: "<#FFD700>"