name: RP_Sign
main: com.Captam4ik.rpsign.RPSignPlugin
version: 2.0
api-version: 1.21
folia-supported: true
description: "Resource Pack Manager via Signs & Commands"
authors: ["Captam4ik"]
website: "https://github.com/Cuptam4ik/RP_Sign"
commands:
  rp:
    description: Resourcepack management
    usage: /rp <create|delete|list|help|clear|reload|lang>
